name: pytest_main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov coverage
        pip install -r requirements.txt
        sudo apt install p7zip-full p7zip-rar
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=15 --exclude=./tests/*,./docs/* --max-line-length=127 --statistics
    - name: Prepate test data
      run: |
        mkdir tests/test_data/output1
        mkdir tests/test_data/output2
        mkdir tests/test_data/output3
        7z x tests/test_data/test_data.7z -otests/test_data/output1
        7z x tests/test_data/test_data.7z -otests/test_data/output2
        7z x tests/test_data/test_data.7z -otests/test_data/output3
    - name: Test with pytest
      run: |
        pytest --cov --cov-branch --cov-report term-missing --cov-append
        coverage json
        echo "COV_PERC=$(python tests/json_parse.py)" >> $GITHUB_ENV
        echo "${{ env.COV_PERC }}"
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_BADGE_SECRET }}
        gistID: b7ce3f2fa674521d574e3830d7970724
        filename: coverage_total.json
        label: Coverage
        message: ${{ env.COV_PERC }}
        color: blue
